### ISSUE TITLE
Add Experiment Wide Settings button

### ISSUE THREAD

**Issue by juliusjgm12** [thartbm/PyVMEC#35]
- Toggle Fullscreen
- Flip-Screen
- Use images instead of cursors (Directory) -> Point to a directory?
(For both target and cursors)

**Comment by thartbm** [comment]
Let's make a branch now. PyVMEC 0.9 works, we can add functionality, but that should not damage what we already have in the master branch?

**Comment by juliusjgm12** [comment]
Sure do you want me to set that up or can you? I've never actually made a
branch before.

**Comment by thartbm** [comment]
Me either! Go ahead and figure out how to do it...

**Comment by juliusjgm12** [comment]
Question! Do you want the target and home to both be customizable?

**Comment by juliusjgm12** [comment]
At the moment every stim object is customizable :)

**Comment by thartbm** [comment]
What do you mean they are both customizable?

What we want for the images is that we can assign an arbitrary number of image pairs to make it more interesting. So it would be a golf-ball (cursor) and hole (target), bone (cursor) and doggy (target) and so on and so on. Mixing them up doesn't make sense all the time (moving the hole to the golf-ball) although in some cases it might work (move the bone to the hole) but we should have a simple solution. For example: we only allow gifs or pngs, or one of the two. So that we would have some files like this:
cursor001.png
target001.png
cursor002.png
target002.png
cursor003.png
...
And we put those in a folder that we can store in the experiment definition (or maybe it has to go somewhere specific, such as in the experiment folder?)

Your job is to first come up with a sensible proposal and then I say 'yay' or 'nay' (in which case I should also say why it wouldn't work and perhaps how to improve it). And once there is a 'yay' you implement it.

So let's take this as your first proposal: explain to me in detail how we can set the cursor/target image pairs? Also: is it all on github yet?

**Comment by juliusjgm12** [comment]
Yes it's all on github already. You can test it out for yourself in the new branch, it currently detects png, jpeg, and jpg files. What I've got so far is a way to set specific images for each stimulus seperately (cursor, target, and home). You can toggle each custom stimulus on or off using a checkbox. above a filepicker. Beside each filepicker is a small bitmap that shows a preview of the chosen images.

What I propose to implement arbitrary numbers of image pairs is this.

I've already got the framework that grabs file directories and saves them into the experiment settings. What I can do now, is create a way to save chosen image pairs which could then be named, saved, and shown in a list box in the settings menu. This way you could scroll through each saved image pair in the list box and see what images are selected along with their previews.

Please test out how it's currently implemented, and you might get a better idea of what I mean.
