### ISSUE TITLE
error when using monitor 1

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#42]
Not sure what's going on, it's likely the same thing I had before when trying to use XLib to read out mouse position from an external monitor. Here's the error message:

```
current position:  [1116, 66]
current position:  [-15, 361]
current position:  [11, 357]
2.5523 	WARNING 	Movie2 stim could not be imported and won't be available
146.3359 	WARNING 	Monitor specification not found. Creating a temporary one...
146.3387 	WARNING 	User requested fullscreen with size [3600 1080], but screen is actually [1920, 1080]. Using actual size
current position:  [1065, 51]
203.2454 	WARNING 	Monitor specification not found. Creating a temporary one...
203.2477 	WARNING 	User requested fullscreen with size [3600 1080], but screen is actually [1680, 1050]. Using actual size

```

**Comment by juliusjgm12** [comment]
Are you still getting this error message? When I use an external monitor at home (as the secondary monitor in display settings and 1 in the global settings) it works properly. I have the main monitor on the left and the secondary monitor on the right though. That might be the issue?

Try changing the display settings so that the screen that the experiment is running in is the secondary monitor and is on the right side of the main monitor. 
![image](https://user-images.githubusercontent.com/32819546/45603315-20051780-b9f9-11e8-81e6-7ff92202fec9.png)

**Comment by juliusjgm12** [comment]
Above are the monitor settings i used when programming the fix with an external monitor
